var sessions = {
    category: [
        {
            name: "Writing Skills",
            topics: [
                {
                    topic: "Critical Thinking & Writing repeat",
                    startDate: "19/09/2016",
                    finishDate: "19/09/2016",
                    days: "Mo",
                    time: "13:00 - 14:30",
                    noOfSessions: "1",
                    placesAvailable: "6",
                    targetGroup: "all students",
                    room: "CB11.04.101",
                    covers: [
                         "What it means to think, read and write critically in an academic context",
                         "Distinguishing between descriptive and critical/analytical writing",
                         "Finding your academic voice",
                         "Reviewing the language of critical writing",
                         "Critical reading and thinking activities",
                    ],
                },
                {
                    topic: "Grammar Session 1: Parts of speech (word forms), subject-verb agreement",
                    startDate: "21/09/2016",
                    finishDate: "21/09/2016",
                    days: "We",
                    time: "11:00 - 12:30",
                    noOfSessions: "1",
                    placesAvailable: "10",
                    targetGroup: "all students",
                    room: "CB10.02.410",
                    covers: [
                         "Parts of speech (word forms), subject-verb agreement",
                    ],
                },
                {
                    topic: "Editing and Proofreading",
                    startDate: "27/09/2016",
                    finishDate: "27/09/2016",
                    days: "Tu",
                    time: "17:00 - 18:30",
                    noOfSessions: "1",
                    placesAvailable: "26",
                    targetGroup: "all students",
                    room: "CB10.02.470",
                    covers: [
                         "Editing to ensure that you have answered the question",
                         "Proofreading your writing for grammatical accuracy",
                         "Using a checklist for editing and proofreading",
                    ],
                },
                {
                    topic: "Grammar Session 2: Verb tenses & reporting verbs",
                    startDate: "28/09/2016",
                    finishDate: "28/09/2016",
                    days: "We",
                    time: "11:00 - 12:30",
                    noOfSessions: "1",
                    placesAvailable: "13",
                    targetGroup: "all students",
                    room: "CB10.02.410",
                    covers: [
                         "Verbs & tenses, reporting verbs",
                    ],
                },
                {
                    topic: "Grammar Session 3: Articles, prepositions & punctuation",
                    startDate: "05/10/2016",
                    finishDate: "05/10/2016",
                    days: "We",
                    time: "11:00 - 12:30",
                    noOfSessions: "1",
                    placesAvailable: "14",
                    targetGroup: "all students",
                    room: "CB05C.01.29",
                    covers: [
                         "Articles, prepositions, punctuation",
                    ],
                },
                {
                    topic: "Editing and Proofreading (Repeat)",
                    startDate: "06/10/2016",
                    finishDate: "06/10/2016",
                    days: "Th",
                    time: "12:00 - 13:30",
                    noOfSessions: "1",
                    placesAvailable: "34",
                    targetGroup: "all students",
                    room: "CB05B.03.026",
                    covers: [
                         "Editing to ensure that you have answered the question",
                         "Proofreading your writing for grammatical accuracy",
                         "Using a checklist for editing and proofreading",
                    ],
                },
            ],
        },
        {
            name: "Presentation + Speaking Skills",
            topics: [
                {
                    topic: "Giving a Presentation",
                    startDate: "42633",
                    finishDate: "42633",
                    days: "Tu",
                    time: "17:00 - 18:30",
                    noOfSessions: "1",
                    placesAvailable: "11",
                    targetGroup: "all students",
                    room: "CB10.02.450B",
                    covers: [
                         "How to plan, organise and structure your oral presentation",
                         "How to use visual aids effectively",
                         "How to calm your nerves",
                         "How to enhance your clarity in speech",
                    ],
                },
                {
                    topic: "Practising Pronunciation (session 5)",
                    startDate: "42635",
                    finishDate: "42635",
                    days: "Th",
                    time: "12:00 - 13:30",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "non-English speaking background students",
                    room: "CB05B.03.026",
                    covers: [
                         "Learn more about English pronunciation and how to speak clearly",
                         "Lots of opportunities to practise pronunciation with native speakers of English and other students",
                         "Get immediate feedback on how you can improve your pronunciation",
                    ],
                },
                {
                    topic: "Practising Pronunciation (session 6)",
                    startDate: "42642",
                    finishDate: "42642",
                    days: "Th",
                    time: "12:00 - 13:30",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "non-English speaking background students",
                    room: "CB05B.03.026",
                    covers: [
                         "Learn more about English pronunciation and how to speak clearly",
                         "Lots of opportunities to practise pronunciation with native speakers of English and other students",
                         "Get immediate feedback on how you can improve your pronunciation",
                    ],
                },
                {
                    topic: "Giving a Presentation repeat",
                    startDate: "42643",
                    finishDate: "42643",
                    days: "Fr",
                    time: "12:00 - 13:30",
                    noOfSessions: "1",
                    placesAvailable: "25",
                    targetGroup: "all students",
                    room: "CB05B.03.28",
                    covers: [
                         "How to plan, organise and structure your oral presentation",
                         "How to use visual aids effectively",
                         "How to calm your nerves",
                         "How to enhance your clarity in speech",
                    ],
                },
            ],
        },
        {
            name: "Study + Reading Skills",
            topics: [
                {
                    topic: "Understanding Turnitin repeat",
                    startDate: "42639",
                    finishDate: "42639",
                    days: "Mo",
                    time: "13:00 - 14:30",
                    noOfSessions: "1",
                    placesAvailable: "27",
                    targetGroup: "all students",
                    room: "CB11.04.101",
                    covers: [
                         "What is Turnitin?",
                         "What does the similarity index mean?",
                         "How to understand a Turnitin report",
                         "How to improve your writing using a Turnitin report",
                    ],
                },
                {
                    topic: "Preparing for Exams",
                    startDate: "42647",
                    finishDate: "42647",
                    days: "Tu",
                    time: "17:00 - 18:30",
                    noOfSessions: "1",
                    placesAvailable: "31",
                    targetGroup: "All students",
                    room: "CB06.06.115",
                    covers: [
                         "How to revise and prepare for your exams",
                         "Different exam questiton types, and how to answer them",
                         "How to plan strategically so you can perform well in exam",
                         "Using past year exam papers to help you plan and prepare",
                         "Other practical advice and tips",
                    ],
                },
                {
                    topic: "Preparing for Exams (Repeat)",
                    startDate: "42650",
                    finishDate: "42650",
                    days: "Fr",
                    time: "12:00 - 13:30",
                    noOfSessions: "1",
                    placesAvailable: "34",
                    targetGroup: "all student",
                    room: "CB05B.03.28",
                    covers: [
                         "How to revise and prepare for your exams",
                         "Different exam questiton types, and how to answer them",
                         "How to plan strategically so you can perform well in exam",
                         "Using past year exam papers to help you plan and prepare",
                         "Other practical advice and tips",
                    ],
                },
            ],
        },
        {
            name: "Communication for Employment",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "WriteNow! Writing Support sessions",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "FY Nursing (Standard) Assignment Writing",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "FY Nursing (Accelerated EN/GE) Assignment Writing",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "U:PASS",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "U:PASSwrite for First Year Nursing students ONLY",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "U:PASSwrite for 31265 Communication for IT Professionals",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "U:PASSwrite for 48122 Engineering Practice Review 1",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "U:PASSwrite for 21129 Managing People & Organisation",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "Conversations@UTS (registration not required)",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "Grammar workshops for PG Science students",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
        {
            name: "31281 System Development Project testing",
            topics: [
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
                {
                    topic: "TOPIC",
                    startDate: "DATE",
                    finishDate: "DATE",
                    days: "DAY",
                    time: "TIME",
                    noOfSessions: "1",
                    placesAvailable: "0",
                    targetGroup: "all students",
                    room: "ROOM",
                    covers: [
                        "item 1",
                        "item 2",
                        "item 3",
                    ],
                },
            ],
        },
    ]
}